# See full Decap documentation for further configuration: https://decapcms.org/docs/intro/
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: src/assets/images/products # Location where files will be stored in the repo - adjusted to store all images, including products and blogs.
public_folder: src/assets/images/products  # Ensure that this path matches the media_folder path above.
site_url: https://infopcsba.com/ # Displays a link to home page in the top-right corner of the CMS dashboard
logo_url: https://codestitch.app/frontend/images/logo.png # Change URL to a link to the image you want to use, no file paths, must be a URL

collections:
  - name: "products" # New collection for products
    label: "Product" # Used in the admin dashboard UI
    editor:
      preview: false
    folder: "src/content/products" # The path to the folder where the product entries are stored
    create: true # Allow users to create new product entries
    identifier_field: "name"
    slug: "{{name}}-{{price}}"
    format: "json" # Save entries in JSON format
    fields: # The fields for each product
      - { label: "Nom de produit", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Prix (DZD)", name: "price", widget: "number", min: 0 , hint: "EXAMPLE : \"1500\"" }
      - { label: "Promotion (DZD) [Moins cher que le prix initial]", name: "offer", widget: "number", min: 0, required: false , hint: "EXAMPLE : \"1300\" "}
      - { label: "Image", name: "image", widget: "image" }
      - label: "Photos additionnelles"
        name: "images"
        widget: "list"
        allow_add: true
        required: false
        fields:
          - { label: "Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["ordinateur de bureau", "ordinateur portable", "gaming", "audio", "souris", "clavier", "câbles", "accessoires", "écrans"], required: false, hint: "Sélectionner les tags pour catégoriser les produits" } # Tags with auto-complete