// This file gets generated by Astro automatically. It deals with types for TypeScript purposes.
/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
/// <reference types="../.astro/astro-i18n.d.ts" />
/// <reference types="../.astro/i18next.d.ts" />
